openapi: 3.0.3
info:
  title: Horizon
  version: 0.0.1
tags:
  - name: account
    description: 'Users interact with the Stellar network through accounts. Everything else in the ledger—assets, offers, trustlines, etc. are owned by accounts, and accounts must authorize all changes to the ledger through signed transactions.'
  - name: assets
    description: 'Assets are representations of value issued on the Stellar network. An asset consists of a type, code, and issuer.'
paths:
  '/accounts/{account_id}':
    get:
      tags:
        - account
      summary: Retrieve an Account
      description: 'The single account endpoint provides information on a specific account. The balances section in the response will also list all the trustlines this account has established, including trustlines that haven’t been authorized yet.'
      operationId: RetrieveAnAccount
      parameters:
        - name: account_id
          in: path
          required: true
          description: This account’s public key encoded in a base32 string representation.
          schema:
            type: string
            example: GDMQQNJM4UL7QIA66P7R2PZHMQINWZBM77BEBMHLFXD5JEUAHGJ7R4JZ
      responses:
        '200':
          description: OK
  '/accounts/{account_id}/operations':
    get:
      tags:
        - account
      summary: Retrieve an Account's Operations
      description: 'This endpoint represents successful operations for a given account and can be used in streaming mode. Streaming mode allows you to listen for new operations for this account as they are added to the Stellar ledger. If called in streaming mode, Horizon will start at the earliest known operation unless a cursor is set, in which case it will start from that cursor. By setting the cursor value to now, you can stream operations created since your request time.'
      operationId: GetOperationsByAccountid
      parameters:
        - $ref: '#/paths/~1accounts~1%7Baccount_id%7D/get/parameters/0'
        - name: cursor
          in: query
          required: false
          description: A number that points to a specific location in a collection of responses and is pulled from the paging_token value of a record.
          schema:
            type: integer
            example: 6606617478959105
        - name: order
          in: query
          required: false
          description: 'A designation of the order in which records should appear. Options include asc (ascending) or desc (descending). If this argument isn’t set, it defaults to asc.'
          schema:
            type: integer
            enum:
              - asc
              - desc
        - name: limit
          in: query
          required: false
          description: 'The maximum number of records returned. The limit can range from 1 to 200 - an upper limit that is hardcoded in Horizon for performance reasons. If this argument isn’t designated, it defaults to 10.'
          schema:
            type: integer
            example: 10
        - name: includefailed
          in: query
          required: false
          description: Set to true to include failed operations in results. Options include true and false.
          schema:
            type: boolean
            enum:
              - true
              - false
      responses:
        '200':
          description: OK
