components:
  parameters:
    AssetParam:
      name: asset
      in: query
      required: false
      description: An issued asset represented as “Code:IssuerAccountID”. Every account in the response will have a trustline for the given asset.
    SponserParam: 
      name: sponser
      in: query
      required: false
      description: Account ID of the sponsor. Every account in the response will either be sponsored by the given account ID or have a subentry (trustline, offer, or data entry) which is sponsored by the given account ID. 
      schema:
        type: string
        example: GDMQQNJM4UL7QIA66P7R2PZHMQINWZBM77BEBMHLFXD5JEUAHGJ7R4JZ
    SignerParam:
      name: signer
      in: query
      required: false
      description: Account ID of the signer. Every account in the response will have the given account ID as a signer.    
      schema:
        type: string
        example: GDMQQNJM4UL7QIA66P7R2PZHMQINWZBM77BEBMHLFXD5JEUAHGJ7R4JZ   
    CursorParam: 
      name: cursor
      in: query
      required: false
      description: A number that points to a specific location in a collection of responses and is pulled from the paging_token value of a record.
      schema:
        type: integer
        example: 6606617478959105
    LimitParam:
      name: limit
      in: query
      required: false
      description: The maximum number of records returned. The limit can range from 1 to 200 - an upper limit that is hardcoded in Horizon for performance reasons. If this argument isn’t designated, it defaults to 10.
      schema:
        type: integer
        example: 10
    AccountIDParam:
      name: account_id
      in: path
      required: true
      description: This account’s public key encoded in a base32 string representation.  
      schema:
        type: string
        example: GDMQQNJM4UL7QIA66P7R2PZHMQINWZBM77BEBMHLFXD5JEUAHGJ7R4JZ
    OrderParam:
      name: order
      in: query
      required: false
      description: A designation of the order in which records should appear. Options include asc (ascending) or desc (descending). If this argument isn’t set, it defaults to asc.    
      schema:
        type: string
        enum:
          - asc
          - desc
    IncludeFailedParam:
      name: includefailed
      in: query
      required: false
      description: Set to true to include failed operations in results. Options include true and false.
      schema:
        type: boolean
        enum:
          - true
          - false
    LiquidityPoolParam:
      name: liqudity_pool
      in: query
      required: false
      description: With this parameter, the results will include only accounts which have trustlines to the specified liquidity pool.
    JoinParam:
      name: join  
      in: query
      required: false
      description: Set to transactions to include the transactions which created each of the operations in the response.
    DataParam:
      name: key
      in: path
      required: true
      description: The key name for this data.  
      schema:
        type: string
        example: config.memo_required  