components:
  parameters:
    AccountIDParam:
      name: account_id
      in: path
      required: true
      description: This account’s public key encoded in a base32 string representation.  
      schema:
        type: string
        example: GDMQQNJM4UL7QIA66P7R2PZHMQINWZBM77BEBMHLFXD5JEUAHGJ7R4JZ
    AssetCodeParam:
      name: asset_code
      in: query
      required: false
      description: The code of the asset you would like to filter by.
    AssetIssuerParam:
        name: asset_issuer
        in: query
        required: false
        description: The Stellar address of the issuer for the asset you would like to filter by. 
    AssetParam:
      name: asset
      in: query
      required: false
      description: An issued asset represented as “Code:IssuerAccountID”. Every account in the response will have a trustline for the given asset.
    BaseAssetCodeParam:
      name: base_asset_code
      in: query
      required: false
      description: The code for the base asset.
      schema:
        type: string
        example: USD
    BaseAssetIssuerParam:
      name: base_asset_issuer
      in: query
      required: false
      description: The Stellar address of the base asset’s issuer.
      schema:
        type: string
        example: GDUKMGUGDZQK6YHYA5Z6AY2G4XDSZPSZ3SW5UN3ARVMO6QSRDWP5YLEX
    BaseAssetTypeParam:
      name: base_asset_type
      in: query
      required: false
      description: The type for the base asset. Either native, credit_alphanum4, or credit_alphanum12.
      schema:
        type: string
        enum:
          - native
          - credit_alphanum4
          - credit_alphanum12
    BuyingAssetCodeParam:
      name: buying_asset_code
      in: query
      required: false
      description: The code for the buying asset. 
    BuyingAssetIssuerParam:
      name: buying_asset_issuer
      in: query
      required: false
      description: The Stellar address of the buying asset’s issuer.
    BuyingAssetTypeParam:
      name: buying_asset_type
      in: query
      required: false
      description: The type for the buying asset. Either native, credit_alphanum4, or credit_alphanum12.
      schema:
        type: string
        enum:
          - native
          - credit_alphanum4
          - credit_alphanum12   
    CounterAssetCodeParam:
      name: counter_asset_code
      in: query
      required: false
      description: The code for the counter asset.
    CounterAssetIssuerParam:
      name: counter_asset_issuer
      in: query
      required: false
      description: The Stellar address of the counter asset’s issuer.
      schema:
        type: string
        example: GDUKMGUGDZQK6YHYA5Z6AY2G4XDSZPSZ3SW5UN3ARVMO6QSRDWP5YLEX
    CounterAssetTypeParam:
      name: counter_asset_type
      in: query
      required: false
      description: The type for the counter asset. Either native, credit_alphanum4, or credit_alphanum12.
      schema:
        type: string
        enum:
          - native
          - credit_alphanum4
          - credit_alphanum12 
    CursorParam: 
      name: cursor
      in: query
      required: false
      description: A number that points to a specific location in a collection of responses and is pulled from the paging_token value of a record.
      schema:
        type: integer
        example: 6606617478959105
    DataParam:
      name: key
      in: path
      required: true
      description: The key name for this data.  
      schema:
        type: string
        example: config.memo_required
    IncludeFailedParam:
      name: includefailed
      in: query
      required: false
      description: Set to true to include failed operations in results. Options include true and false.
      schema:
        type: boolean
        enum:
          - true
          - false
    JoinParam:
      name: join  
      in: query
      required: false
      description: Set to transactions to include the transactions which created each of the operations in the response.                 
    LimitParam:
      name: limit
      in: query
      required: false
      description: The maximum number of records returned. The limit can range from 1 to 200 - an upper limit that is hardcoded in Horizon for performance reasons. If this argument isn’t designated, it defaults to 10.
      schema:
        type: integer
        example: 10
    LiquidityPoolParam:
      name: liqudity_pool
      in: query
      required: false
      description: With this parameter, the results will include only accounts which have trustlines to the specified liquidity pool.    
    OfferIdParam:
      name: offer_id
      in: query
      required: false
      description: The offer ID. Used to filter for trades originating from a specific offer. 
    OfferIDParam:
      name: offer_id
      in: path
      required: true
      description: A unique identifier for this offer.
    OrderParam:
      name: order
      in: query
      required: false
      description: A designation of the order in which records should appear. Options include asc (ascending) or desc (descending). If this argument isn’t set, it defaults to asc.    
      schema:
        type: string
        enum:
          - asc
          - desc    
    SellerParam:
      name: seller
      in: query
      required: false
      description: The account ID of the offer creator.
    SellingAssetCodeParam:
      name: selling_asset_code
      in: query
      required: false
      description: The code for the selling asset.
    SellingAssetIssuerParam:
      name: selling_asset_issuer
      in: query
      required: false
      description: The Stellar address of the selling asset’s issuer. 
    SellingAssetTypeParam:
      name: selling_asset_type
      in: query
      required: false
      description: The type for the selling asset. Either native, credit_alphanum4, or credit_alphanum12.
      schema:
        type: string
        enum:
          - native
          - credit_alphanum4
          - credit_alphanum12 
    SignerParam:
      name: signer
      in: query
      required: false
      description: Account ID of the signer. Every account in the response will have the given account ID as a signer.    
      schema:
        type: string
        example: GDMQQNJM4UL7QIA66P7R2PZHMQINWZBM77BEBMHLFXD5JEUAHGJ7R4JZ      
    SponsorParam: 
      name: sponser
      in: query
      required: false
      description: Account ID of the sponsor. Every account in the response will either be sponsored by the given account ID or have a subentry (trustline, offer, or data entry) which is sponsored by the given account ID. 
      schema:
        type: string
        example: GDMQQNJM4UL7QIA66P7R2PZHMQINWZBM77BEBMHLFXD5JEUAHGJ7R4JZ
    TradeTypeParam:
      name: trade_type
      in: query
      required: false
      description: Can be set to all, orderbook, or liquidity_pools to filter only trades executed across a given mechanism.
      schema:
        type: string
        enum:
          - all
          - orderbook
          - liquidity_pools
    
    
   
   
  